--[[ MyGame.Sample.Equipment

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 24.3.25

  Declared by  : 
  Rooting type : MyGame.Sample.Monster ()

--]]

local Equipment = {
  NONE = 0,
  Weapon = 1,
}

return Equipment