--[[ MyGame.Sample.Weapon

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 24.3.25

  Declared by  : 
  Rooting type : MyGame.Sample.Monster ()

--]]

local flatbuffers = require('flatbuffers')

local Weapon = {}
local mt = {}

function Weapon.New()
  local o = {}
  setmetatable(o, {__index = mt})
  return o
end

function mt:Init(buf, pos)
  self.view = flatbuffers.view.New(buf, pos)
end

function mt:Name()
  local o = self.view:Offset(4)
  if o ~= 0 then
    return self.view:String(self.view.pos + o)
  end
end

function mt:Damage()
  local o = self.view:Offset(6)
  if o ~= 0 then
    return self.view:Get(flatbuffers.N.Int16, self.view.pos + o)
  end
  return 0
end

function Weapon.Start(builder)
  builder:StartObject(2)
end

function Weapon.AddName(builder, name)
  builder:PrependUOffsetTRelativeSlot(0, name, 0)
end

function Weapon.AddDamage(builder, damage)
  builder:PrependInt16Slot(1, damage, 0)
end

function Weapon.End(builder)
  return builder:EndObject()
end

return Weapon